# Generated by Django 6.0.5 on 2026-05-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloodInventrory',
            new_name='BloodInventory',
        ),
    ]
