# Generated by Django 6.0.5 on 2026-06-03 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank_app', '0004_hospital_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='donor_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='phone',
        ),
        migrations.AddField(
            model_name='donor',
            name='available_for_donation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='consent_to_contact',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='medical_issues',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
