# Generated by Django 6.0.5 on 2026-06-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank_app', '0006_alter_donor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
