# Generated by Django 6.0.5 on 2026-06-07 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank_app', '0007_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='request_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2026, 6, 7)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
